/**
 * This file is automatically generated by scripts/generate-local-artists-metadata.mjs.
 * Do not edit manually. Run the script to regenerate.
 */

export const LOCAL_IMPORT_ARTISTS_METADATA: Record<string, {
  id: string;
  sourceArtistName?: string;
  sourceArtistImageUrl?: string;
  appleMusicUrl?: string;
  fetchStatus: 'success' | 'pending' | 'failed' | 'not_found';
}> = {
  "tnt": {
    "id": "tnt",
    "sourceArtistName": "时代少年团",
    "sourceArtistImageUrl": "https://is1-ssl.mzstatic.com/image/thumb/Features221/v4/8a/ed/09/8aed0981-a795-1605-c925-cd119cdc0656/mzl.fhjohtjr.jpg/600x600cc.webp",
    "appleMusicUrl": "https://music.apple.com/us/artist/tnt/1445054554?uo=4",
    "fetchStatus": "success"
  },
  "ma-jia-qi": {
    "id": "ma-jia-qi",
    "sourceArtistName": "马嘉祺",
    "sourceArtistImageUrl": "https://is1-ssl.mzstatic.com/image/thumb/Features221/v4/40/65/2f/40652f7c-1e82-e316-227f-12e1dfb65f38/mzl.ftdahzab.jpg/600x600cc.webp",
    "appleMusicUrl": "https://music.apple.com/us/artist/ma-jiaqi/1383307631?uo=4",
    "fetchStatus": "success"
  },
  "yan-hao-xiang": {
    "id": "yan-hao-xiang",
    "sourceArtistName": "严浩翔",
    "sourceArtistImageUrl": "https://is1-ssl.mzstatic.com/image/thumb/Features221/v4/9e/89/75/9e897534-d678-98bf-15a2-8ea0a0e27810/mzl.edqjogub.jpg/600x600cc.webp",
    "appleMusicUrl": "https://music.apple.com/us/artist/yan-haoxiang/1489973276?uo=4",
    "fetchStatus": "success"
  },
  "he-jun-lin": {
    "id": "he-jun-lin",
    "sourceArtistName": "贺峻霖",
    "sourceArtistImageUrl": "https://is1-ssl.mzstatic.com/image/thumb/Features221/v4/a5/67/96/a567967e-d356-85c7-c6ec-67a55610e027/mzl.chsvshnw.jpg/600x600cc.webp",
    "appleMusicUrl": "https://music.apple.com/us/artist/he-junlin/1440471248?uo=4",
    "fetchStatus": "success"
  },
  "song-ya-xuan": {
    "id": "song-ya-xuan",
    "sourceArtistName": "宋亞軒",
    "sourceArtistImageUrl": "https://is1-ssl.mzstatic.com/image/thumb/Features211/v4/54/f4/b5/54f4b524-dff4-7254-34d0-716300083ce7/mzl.hezdjqwm.jpg/600x600cc.webp",
    "appleMusicUrl": "https://music.apple.com/us/artist/song-yaxuan/1383307645?uo=4",
    "fetchStatus": "success"
  },
  "liu-yao-wen": {
    "id": "liu-yao-wen",
    "sourceArtistName": "刘耀文",
    "sourceArtistImageUrl": "https://i.scdn.co/image/ab6761610000e5eb5fc6952589a9577cc79b992f",
    "fetchStatus": "success"
  },
  "zhang-zhen-yuan": {
    "id": "zhang-zhen-yuan",
    "sourceArtistName": "张真源",
    "sourceArtistImageUrl": "https://i.scdn.co/image/ab6761610000e5ebd02f72278e43906560076471",
    "fetchStatus": "success"
  },
  "ding-chengxin": {
    "id": "ding-chengxin",
    "sourceArtistName": "丁程鑫",
    "sourceArtistImageUrl": "https://i.scdn.co/image/ab6761610000e5ebf5091a123f3028b8509df348",
    "fetchStatus": "success"
  },
  "tf-family-3rd": {
    "id": "tf-family-3rd",
    "sourceArtistName": "TF家族三代",
    "sourceArtistImageUrl": "https://i.scdn.co/image/ab67706c0000bebbbb19830531235655755140f7",
    "fetchStatus": "success"
  },
  "jay-chou": {
    "id": "jay-chou",
    "sourceArtistName": "周杰倫",
    "sourceArtistImageUrl": "https://is1-ssl.mzstatic.com/image/thumb/AMCArtistImages211/v4/6d/53/0e/6d530e69-ce17-1c15-7605-b267ef760ea1/ami-identity-8cbee1395c1dbfa4daf6d4c572503010-2026-03-24T12-21-24.021Z_cropped.png/600x600cc.webp",
    "appleMusicUrl": "https://music.apple.com/us/artist/jay-chou/300117743?uo=4",
    "fetchStatus": "success"
  },
  "mayday": {
    "id": "mayday",
    "sourceArtistName": "五月天",
    "sourceArtistImageUrl": "https://is1-ssl.mzstatic.com/image/thumb/Features211/v4/6d/0c/cd/6d0ccdd6-ce44-a774-2a68-a1a15b1477bb/mzl.tfxrqdgx.jpg/600x600cc.webp",
    "appleMusicUrl": "https://music.apple.com/us/artist/mayday/369211611?uo=4",
    "fetchStatus": "success"
  },
  "jj-lin": {
    "id": "jj-lin",
    "sourceArtistName": "林俊傑",
    "sourceArtistImageUrl": "https://is1-ssl.mzstatic.com/image/thumb/Features126/v4/b9/64/5a/b9645a4b-b66b-a62c-5998-5c99c5bd6e9b/mzl.obbxkbai.jpg/600x600cc.webp",
    "appleMusicUrl": "https://music.apple.com/us/artist/jj-lin/216635866?uo=4",
    "fetchStatus": "success"
  },
  "silence-wang": {
    "id": "silence-wang",
    "sourceArtistName": "汪苏泷",
    "sourceArtistImageUrl": "https://is1-ssl.mzstatic.com/image/thumb/Features211/v4/95/9f/89/959f895f-a08a-3e40-2d22-569cc3b637f9/mzl.xroemfgf.jpg/600x600cc.webp",
    "appleMusicUrl": "https://music.apple.com/us/artist/silence-wang/657686835?uo=4",
    "fetchStatus": "success"
  },
  "zhou-shen": {
    "id": "zhou-shen",
    "sourceArtistName": "周深",
    "sourceArtistImageUrl": "https://is1-ssl.mzstatic.com/image/thumb/Features115/v4/2d/35/6f/2d356fe5-d0b4-e431-052f-853a959f7448/mzl.xoklisgn.jpg/600x600cc.webp",
    "appleMusicUrl": "https://music.apple.com/us/artist/zhou-shen/1154054707?uo=4",
    "fetchStatus": "success"
  },
  "faye-wong": {
    "id": "faye-wong",
    "sourceArtistName": "王菲",
    "sourceArtistImageUrl": "https://is1-ssl.mzstatic.com/image/thumb/Features115/v4/d9/da/f5/d9daf550-3c5f-0c1b-9d75-0b69daa7db33/pr_source.png/600x600cc.webp",
    "appleMusicUrl": "https://music.apple.com/us/artist/faye-wong/41760704?uo=4",
    "fetchStatus": "success"
  },
  "hua-chen-yu": {
    "id": "hua-chen-yu",
    "sourceArtistName": "华晨宇",
    "sourceArtistImageUrl": "https://is1-ssl.mzstatic.com/image/thumb/Features211/v4/c7/1c/b9/c71cb932-d71c-32da-e178-e3519074e367/mzl.qcojryjv.jpg/600x600cc.webp",
    "appleMusicUrl": "https://music.apple.com/us/artist/hua-chenyu/919255386?uo=4",
    "fetchStatus": "success"
  },
  "joker-xue": {
    "id": "joker-xue",
    "sourceArtistName": "薛之谦",
    "sourceArtistImageUrl": "https://is1-ssl.mzstatic.com/image/thumb/Features211/v4/09/70/0a/09700ae8-6360-cf09-fd2a-d08d5847e74d/mzl.uusgipnq.jpg/600x600cc.webp",
    "appleMusicUrl": "https://music.apple.com/us/artist/joker-xue/160809474?uo=4",
    "fetchStatus": "success"
  },
  "bella-yao": {
    "id": "bella-yao",
    "sourceArtistName": "姚贝娜",
    "sourceArtistImageUrl": "https://is1-ssl.mzstatic.com/image/thumb/Music69/v4/dc/4b/77/dc4b770b-fcb7-4211-debf-b2e55156ebe1/yongcun.jpg/600x600cc.webp",
    "appleMusicUrl": "https://music.apple.com/us/artist/bella-yao/834182538?uo=4",
    "fetchStatus": "success"
  },
  "li-jian": {
    "id": "li-jian",
    "sourceArtistName": "李健",
    "sourceArtistImageUrl": "https://is1-ssl.mzstatic.com/image/thumb/Features211/v4/1b/ba/81/1bba81fa-e580-a412-18c5-ec1578610794/mzl.tdcvklhi.jpg/600x600cc.webp",
    "appleMusicUrl": "https://music.apple.com/us/artist/li-jian/159211091?uo=4",
    "fetchStatus": "success"
  },
  "liu-yu-ning": {
    "id": "liu-yu-ning",
    "sourceArtistName": "摩登兄弟刘宇宁",
    "sourceArtistImageUrl": "https://is1-ssl.mzstatic.com/image/thumb/Features211/v4/cb/ab/2c/cbab2cdf-1cb5-f63e-db08-ed8eeceac061/mzl.gtdtavpb.jpg/600x600cc.webp",
    "appleMusicUrl": "https://music.apple.com/us/artist/liu-yu-ning/1424089710?uo=4",
    "fetchStatus": "success"
  },
  "gem": {
    "id": "gem",
    "sourceArtistName": "鄧紫棋",
    "sourceArtistImageUrl": "https://is1-ssl.mzstatic.com/image/thumb/Features122/v4/fc/4b/eb/fc4bebe6-9b10-481e-b406-3d0e299943cf/mzl.pjxmoluh.png/600x600cc.webp",
    "appleMusicUrl": "https://music.apple.com/us/artist/g-e-m/425208570?uo=4",
    "fetchStatus": "success"
  },
  "stefanie-sun": {
    "id": "stefanie-sun",
    "sourceArtistName": "孫燕姿",
    "sourceArtistImageUrl": "https://is1-ssl.mzstatic.com/image/thumb/Features221/v4/65/ad/54/65ad548d-b327-61fd-2430-f77a2fdd1805/mzl.dlsgqkzw.jpg/600x600cc.webp",
    "appleMusicUrl": "https://music.apple.com/us/artist/yanzi-sun/83405200?uo=4",
    "fetchStatus": "success"
  },
  "joey-yung": {
    "id": "joey-yung",
    "sourceArtistName": "容祖兒",
    "sourceArtistImageUrl": "https://is1-ssl.mzstatic.com/image/thumb/Features125/v4/aa/50/71/aa507147-a40b-0362-13be-e68e342b9616/mzl.cqtmlmws.jpg/600x600cc.webp",
    "appleMusicUrl": "https://music.apple.com/us/artist/joey-yung/370528896?uo=4",
    "fetchStatus": "success"
  },
  "wu-bai": {
    "id": "wu-bai",
    "sourceArtistName": "伍佰",
    "sourceArtistImageUrl": "https://is1-ssl.mzstatic.com/image/thumb/Features125/v4/a9/72/83/a972839c-4b63-13d9-8242-70916372dd7a/mzl.eesymkfj.jpg/600x600cc.webp",
    "appleMusicUrl": "https://music.apple.com/us/artist/wu-bai/327469111?uo=4",
    "fetchStatus": "success"
  },
  "f4": {
    "id": "f4",
    "sourceArtistName": "F4",
    "sourceArtistImageUrl": "https://is1-ssl.mzstatic.com/image/thumb/Features211/v4/48/eb/66/48eb66dd-f6ee-6f96-835c-dd6b1f26f7d7/mzl.kpbyhepm.jpg/600x600cc.webp",
    "appleMusicUrl": "https://music.apple.com/us/artist/f4/137635396?uo=4",
    "fetchStatus": "success"
  },
  "jerry-yan": {
    "id": "jerry-yan",
    "sourceArtistName": "言承旭",
    "sourceArtistImageUrl": "https://is1-ssl.mzstatic.com/image/thumb/Features115/v4/ff/46/51/ff465143-c50d-24a9-ea7a-5745e4251d86/pr_source.png/600x600cc.webp",
    "appleMusicUrl": "https://music.apple.com/us/artist/jerry-yan/320123447?uo=4",
    "fetchStatus": "success"
  },
  "vanness-wu": {
    "id": "vanness-wu",
    "sourceArtistName": "吳建豪",
    "sourceArtistImageUrl": "https://is1-ssl.mzstatic.com/image/thumb/Features221/v4/92/79/89/92798985-41ae-6101-824e-c47c85b98511/mzl.urrwzyzk.jpg/600x600cc.webp",
    "appleMusicUrl": "https://music.apple.com/us/artist/van-ness-wu/289040072?uo=4",
    "fetchStatus": "success"
  },
  "vic-chou": {
    "id": "vic-chou",
    "sourceArtistName": "周渝民",
    "sourceArtistImageUrl": "https://is1-ssl.mzstatic.com/image/thumb/Features125/v4/65/b7/8a/65b78acb-99bb-9e6a-2312-90e5e8d1fc00/pr_source.png/600x600cc.webp",
    "appleMusicUrl": "https://music.apple.com/us/artist/vic-chou/307678942?uo=4",
    "fetchStatus": "success"
  },
  "ashin": {
    "id": "ashin",
    "sourceArtistName": "五月天 阿信",
    "sourceArtistImageUrl": "https://is1-ssl.mzstatic.com/image/thumb/Features125/v4/10/fa/95/10fa954f-c06b-d598-dff9-3ba9d84bc340/mzl.afxszoba.jpg/600x600cc.webp",
    "appleMusicUrl": "https://music.apple.com/us/artist/ashin-chen/185511960?uo=4",
    "fetchStatus": "success"
  },
  "lay-zhang": {
    "id": "lay-zhang",
    "sourceArtistName": "张艺兴",
    "sourceArtistImageUrl": "https://is1-ssl.mzstatic.com/image/thumb/AMCArtistImages211/v4/8b/19/de/8b19dea8-440a-6c1c-41c4-ca83eff38001/6145ab0b-bcac-4ffb-9ae8-c5f2feff8e2f_ami-identity-3088802ce36c8685734ddc9861dcef00-2024-06-14T04-15-17.424Z_cropped.png/600x600cc.webp",
    "appleMusicUrl": "https://music.apple.com/us/artist/lay/1118027719?uo=4",
    "fetchStatus": "success"
  },
  "chen-xue-ran": {
    "id": "chen-xue-ran",
    "sourceArtistName": "陈雪燃",
    "sourceArtistImageUrl": "https://is1-ssl.mzstatic.com/image/thumb/Features125/v4/80/d5/20/80d5205e-e9a8-8979-9253-c5a367b9dd73/mzl.riytxykk.jpg/600x600cc.webp",
    "appleMusicUrl": "https://music.apple.com/us/artist/xueran-chen/1348213979?uo=4",
    "fetchStatus": "success"
  },
  "chen-li": {
    "id": "chen-li",
    "sourceArtistName": "陈粒",
    "sourceArtistImageUrl": "https://is1-ssl.mzstatic.com/image/thumb/Features115/v4/2a/83/6a/2a836a6e-1a08-3c4b-ac1b-2c670be7131e/mzl.dykkpeog.jpg/600x600cc.webp",
    "appleMusicUrl": "https://music.apple.com/us/artist/chen-li/1138469250?uo=4",
    "fetchStatus": "success"
  },
  "dizzy-dizzo": {
    "id": "dizzy-dizzo",
    "sourceArtistName": "蔡詩蕓",
    "sourceArtistImageUrl": "https://is1-ssl.mzstatic.com/image/thumb/Features115/v4/b7/20/4c/b7204cf4-1a1b-f48f-b8bd-6b59dfffa2f3/mzl.orsphxwi.jpg/600x600cc.webp",
    "appleMusicUrl": "https://music.apple.com/us/artist/dominique-tsai/509508968?uo=4",
    "fetchStatus": "success"
  },
  "shan-yi-chun": {
    "id": "shan-yi-chun",
    "sourceArtistName": "单依纯",
    "sourceArtistImageUrl": "https://is1-ssl.mzstatic.com/image/thumb/AMCArtistImages221/v4/f9/c5/09/f9c509a3-28a4-a62a-6fe5-754f50a116cf/file_cropped.png/600x600cc.webp",
    "appleMusicUrl": "https://music.apple.com/us/artist/yichun-shan/1546181214?uo=4",
    "fetchStatus": "success"
  },
  "lu-yuan-yi": {
    "id": "lu-yuan-yi",
    "sourceArtistName": "盧苑儀",
    "sourceArtistImageUrl": "https://is1-ssl.mzstatic.com/image/thumb/Music124/v4/c8/67/a7/c867a738-ff69-b997-022e-5622dc8c24d0/cover.jpg/600x600cc.webp",
    "appleMusicUrl": "https://music.apple.com/us/artist/vivien-loh/1449274873?uo=4",
    "fetchStatus": "success"
  },
  "zhang-yuan": {
    "id": "zhang-yuan",
    "sourceArtistName": "张远",
    "sourceArtistImageUrl": "https://is1-ssl.mzstatic.com/image/thumb/Features221/v4/cc/c7/40/ccc740be-d618-8a79-724f-ab501511e0bf/mzl.uyvxbcsl.jpeg/600x600cc.webp",
    "appleMusicUrl": "https://music.apple.com/us/artist/zhang-yuan/1219951079?uo=4",
    "fetchStatus": "success"
  },
  "zhao-lu-si": {
    "id": "zhao-lu-si",
    "sourceArtistName": "赵露思",
    "sourceArtistImageUrl": "https://is1-ssl.mzstatic.com/image/thumb/Features116/v4/69/ad/94/69ad94dd-3730-1677-a6dc-199508e7dd59/mzl.qsioelci.jpg/600x600cc.webp",
    "appleMusicUrl": "https://music.apple.com/us/artist/rosy/1380598428?uo=4",
    "fetchStatus": "success"
  },
  "su-xing-jie": {
    "id": "su-xing-jie",
    "sourceArtistName": "苏星婕",
    "sourceArtistImageUrl": "https://is1-ssl.mzstatic.com/image/thumb/Music116/v4/51/ca/27/51ca27cb-2dd2-9293-b2ee-be73375fdcca/cover.jpg/600x600cc.webp",
    "appleMusicUrl": "https://music.apple.com/us/artist/xingjie-su/1551599936?uo=4",
    "fetchStatus": "success"
  },
  "zi-yu": {
    "id": "zi-yu",
    "sourceArtistName": "梓渝",
    "sourceArtistImageUrl": "https://is1-ssl.mzstatic.com/image/thumb/Music211/v4/23/db/9a/23db9a63-3e24-0eca-2bc2-5ab2f707701a/cover.jpg/600x600cc.webp",
    "appleMusicUrl": "https://music.apple.com/us/artist/%E6%A2%93%E6%B8%9D/1750939042?uo=4",
    "fetchStatus": "success"
  },
  "chen-xuan-xiao": {
    "id": "chen-xuan-xiao",
    "sourceArtistName": "大泫",
    "sourceArtistImageUrl": "https://is1-ssl.mzstatic.com/image/thumb/Music113/v4/a4/c9/63/a4c9634c-c056-15bf-3dc9-4475b4f07185/cover.jpg/600x600cc.webp",
    "appleMusicUrl": "https://music.apple.com/us/artist/%E5%A4%A7%E6%B3%AB/1410798071?uo=4",
    "fetchStatus": "success"
  },
  "lbi": {
    "id": "lbi",
    "sourceArtistName": "LBI利比",
    "sourceArtistImageUrl": "https://is1-ssl.mzstatic.com/image/thumb/Features122/v4/5f/3e/77/5f3e77f9-d282-edbc-b775-35ebe2b1700f/mzl.zfivghkq.jpg/600x600cc.webp",
    "appleMusicUrl": "https://music.apple.com/us/artist/lbi/1616297807?uo=4",
    "fetchStatus": "success"
  },
  "wang-yan-wei": {
    "id": "wang-yan-wei",
    "sourceArtistName": "王艷薇",
    "sourceArtistImageUrl": "https://is1-ssl.mzstatic.com/image/thumb/AMCArtistImages211/v4/b8/08/0f/b8080f2e-921c-71bd-bfa9-14c072ed10e1/ami-identity-e5854eed1552ad0bebb7192f257f487e-2025-11-24T15-55-16.937Z_cropped.png/600x600cc.webp",
    "appleMusicUrl": "https://music.apple.com/us/artist/evangeline/1233764662?uo=4",
    "fetchStatus": "success"
  },
  "feifei-princess": {
    "id": "feifei-princess",
    "sourceArtistName": "菲菲公主",
    "sourceArtistImageUrl": "https://is1-ssl.mzstatic.com/image/thumb/Music126/v4/67/03/06/6703063a-9b72-ae9b-b23c-8d349453af45/cover.jpg/600x600cc.webp",
    "appleMusicUrl": "https://music.apple.com/us/artist/%E8%8F%B2%E8%8F%B2%E5%85%AC%E4%B8%BB/1578645458?uo=4",
    "fetchStatus": "success"
  },
  "kun": {
    "id": "kun",
    "sourceArtistName": "蔡徐坤",
    "sourceArtistImageUrl": "https://is1-ssl.mzstatic.com/image/thumb/AMCArtistImages211/v4/42/e0/4a/42e04ae4-1f14-efa4-d068-5758c67a3618/file_cropped.png/600x600cc.webp",
    "appleMusicUrl": "https://music.apple.com/us/artist/kun/1421021751?uo=4",
    "fetchStatus": "success"
  },
  "zhang-hao": {
    "id": "zhang-hao",
    "sourceArtistName": "ZHANG HAO",
    "sourceArtistImageUrl": "https://is1-ssl.mzstatic.com/image/thumb/AMCArtistImages211/v4/d2/8e/8a/d28e8a0d-b51b-f1de-8724-0dc902e67117/ami-identity-956ae3a80ad4deae756b0af85e73e72b-2026-01-26T07-55-36.129Z_cropped.png/600x600cc.webp",
    "appleMusicUrl": "https://music.apple.com/us/artist/zhang-hao/1726118073?uo=4",
    "fetchStatus": "success"
  },
  "bruno-mars": {
    "id": "bruno-mars",
    "sourceArtistName": "Bruno Mars",
    "sourceArtistImageUrl": "https://is1-ssl.mzstatic.com/image/thumb/AMCArtistImages211/v4/75/7e/dd/757edd95-3276-ff15-7de3-5c8e8ec87b4c/ami-identity-865f12490d8b5356071cd06a025b5b6a-2026-01-09T05-04-02.540Z_cropped.png/600x600cc.webp",
    "appleMusicUrl": "https://music.apple.com/us/artist/bruno-mars/278873078?uo=4",
    "fetchStatus": "success"
  },
  "seventeen": {
    "id": "seventeen",
    "sourceArtistName": "SEVENTEEN",
    "sourceArtistImageUrl": "https://i.scdn.co/image/ab676161000051748da3a229445fd3cd896cdd5c",
    "fetchStatus": "success"
  },
  "eason-chan": {
    "id": "eason-chan",
    "sourceArtistName": "陈奕迅",
    "sourceArtistImageUrl": "https://i.scdn.co/image/ab6761610000e5eb98f8287600bb918498f8045a",
    "fetchStatus": "success"
  },
  "bts": {
    "id": "bts",
    "sourceArtistName": "BTS",
    "sourceArtistImageUrl": "https://is1-ssl.mzstatic.com/image/thumb/AMCArtistImages221/v4/3c/8d/87/3c8d8721-24fa-0250-7e00-3f1990ccc0c0/ami-identity-5644914dae79e9896405d9b5b7ac9e89-2026-03-20T04-09-55.932Z_cropped.png/600x600cc.webp",
    "appleMusicUrl": "https://music.apple.com/us/artist/bts/883131348?uo=4",
    "fetchStatus": "success"
  },
  "blackpink": {
    "id": "blackpink",
    "sourceArtistName": "BLACKPINK",
    "sourceArtistImageUrl": "https://is1-ssl.mzstatic.com/image/thumb/AMCArtistImages211/v4/72/0c/7d/720c7d75-dff0-97ac-ec79-6639c616412c/ami-identity-2d9111efdb30d9928ef6b549bcef0daf-2026-02-27T04-58-11.825Z_cropped.png/600x600cc.webp",
    "appleMusicUrl": "https://music.apple.com/us/artist/blackpink/1141774019?uo=4",
    "fetchStatus": "success"
  },
  "rose": {
    "id": "rose",
    "sourceArtistName": "ROSÉ",
    "sourceArtistImageUrl": "https://is1-ssl.mzstatic.com/image/thumb/AMCArtistImages211/v4/e5/2b/6f/e52b6f42-d751-aeb2-7c1f-43be133bfabb/ami-identity-02caae62a4b6b93e74586343e6cf896e-2024-10-18T03-52-40.015Z_cropped.png/600x600cc.webp",
    "appleMusicUrl": "https://music.apple.com/us/artist/ros%C3%A9/1406242696?uo=4",
    "fetchStatus": "success"
  },
  "aespa": {
    "id": "aespa",
    "sourceArtistName": "aespa",
    "sourceArtistImageUrl": "https://is1-ssl.mzstatic.com/image/thumb/AMCArtistImages211/v4/46/e2/ba/46e2bad4-ae0e-56dc-6ef3-0ac3f798df1c/ami-identity-a7ba7a1dcf176f3a97d5a241459fcb51-2025-09-03T05-29-01.837Z_cropped.png/600x600cc.webp",
    "appleMusicUrl": "https://music.apple.com/us/artist/aespa/1540251304?uo=4",
    "fetchStatus": "success"
  },
  "ive": {
    "id": "ive",
    "sourceArtistName": "IVE",
    "sourceArtistImageUrl": "https://is1-ssl.mzstatic.com/image/thumb/AMCArtistImages211/v4/6a/65/5b/6a655be8-4c87-849c-290e-e8aaa7f0dcd9/ami-identity-69240dba41883ac416d4effab06e1b2c-2026-02-02T04-43-02.934Z_cropped.png/600x600cc.webp",
    "appleMusicUrl": "https://music.apple.com/us/artist/ive/1594159996?uo=4",
    "fetchStatus": "success"
  },
  "illit": {
    "id": "illit",
    "sourceArtistName": "ILLIT",
    "sourceArtistImageUrl": "https://is1-ssl.mzstatic.com/image/thumb/AMCArtistImages221/v4/fb/03/ac/fb03acfe-1ad6-82df-c7dc-abd394b8e1c9/ami-identity-9853bc1fbd8535d1ca08d437b0b31bd8-2025-11-24T09-11-57.815Z_cropped.png/600x600cc.webp",
    "appleMusicUrl": "https://music.apple.com/us/artist/illit/1734551937?uo=4",
    "fetchStatus": "success"
  },
  "gi-dle": {
    "id": "gi-dle",
    "sourceArtistName": "i-dle",
    "sourceArtistImageUrl": "https://is1-ssl.mzstatic.com/image/thumb/AMCArtistImages211/v4/16/06/83/160683db-3220-1859-5bd4-2ded4a9840d6/ami-identity-da9dd3316026fa2554d986133c5e010a-2026-01-23T00-59-55.205Z_cropped.png/600x600cc.webp",
    "appleMusicUrl": "https://music.apple.com/us/artist/i-dle/1378887586?uo=4",
    "fetchStatus": "success"
  },
  "le-sserafim": {
    "id": "le-sserafim",
    "sourceArtistName": "LE SSERAFIM",
    "sourceArtistImageUrl": "https://is1-ssl.mzstatic.com/image/thumb/AMCArtistImages211/v4/73/84/2f/73842f43-91e9-cedf-088e-d86528a61d45/ami-identity-287a577e8436fb5d4109090a2ba96ce7-2025-10-17T05-29-22.704Z_cropped.png/600x600cc.webp",
    "appleMusicUrl": "https://music.apple.com/us/artist/le-sserafim/1616740364?uo=4",
    "fetchStatus": "success"
  },
  "tws": {
    "id": "tws",
    "sourceArtistName": "TWS",
    "sourceArtistImageUrl": "https://is1-ssl.mzstatic.com/image/thumb/AMCArtistImages221/v4/3e/59/c0/3e59c0b2-d280-2dc2-54be-8316f9191e5c/ami-identity-77a8762b077367e1af60dbea9ea480f3-2025-10-13T04-46-10.042Z_cropped.png/600x600cc.webp",
    "appleMusicUrl": "https://music.apple.com/us/artist/tws/1721226191?uo=4",
    "fetchStatus": "success"
  },
  "zerobaseone": {
    "id": "zerobaseone",
    "sourceArtistName": "ZEROBASEONE",
    "sourceArtistImageUrl": "https://is1-ssl.mzstatic.com/image/thumb/AMCArtistImages211/v4/63/f6/30/63f630d9-62b6-fba9-79e4-3c901224b868/ami-identity-797313e0279b1986753312578c0c4b9c-2026-01-26T07-46-32.933Z_cropped.png/600x600cc.webp",
    "appleMusicUrl": "https://music.apple.com/us/artist/zerobaseone/1693315406?uo=4",
    "fetchStatus": "success"
  },
  "boys-planet": {
    "id": "boys-planet",
    "sourceArtistName": "BOYS II PLANET",
    "sourceArtistImageUrl": "https://is1-ssl.mzstatic.com/image/thumb/Features211/v4/c2/38/c3/c238c30e-fee6-158b-4532-a314aed9be38/mzl.dcdyvdaz.jpg/600x600cc.webp",
    "appleMusicUrl": "https://music.apple.com/us/artist/boys-ii-planet/1819687595?uo=4",
    "fetchStatus": "success"
  },
  "allday-project": {
    "id": "allday-project",
    "sourceArtistName": "ALLDAY PROJECT",
    "sourceArtistImageUrl": "https://is1-ssl.mzstatic.com/image/thumb/AMCArtistImages221/v4/1c/2d/fd/1c2dfdb1-d516-58ed-cf6c-76aab3347eeb/ami-identity-4327295aac550a4f4294284704368d95-2025-11-28T09-33-57.071Z_cropped.png/600x600cc.webp",
    "appleMusicUrl": "https://music.apple.com/us/artist/allday-project/1819675764?uo=4",
    "fetchStatus": "success"
  },
  "cortis": {
    "id": "cortis",
    "sourceArtistName": "CORTIS",
    "sourceArtistImageUrl": "https://is1-ssl.mzstatic.com/image/thumb/AMCArtistImages221/v4/73/c8/6b/73c86bec-c4aa-6021-6d2d-12c882536ec3/ami-identity-0d84d3c3e9806017af59a5b75a59ce0e-2025-08-11T00-11-41.060Z_cropped.png/600x600cc.webp",
    "appleMusicUrl": "https://music.apple.com/us/artist/cortis/1831651635?uo=4",
    "fetchStatus": "success"
  },
  "hearts2hearts": {
    "id": "hearts2hearts",
    "sourceArtistName": "Hearts2Hearts",
    "sourceArtistImageUrl": "https://is1-ssl.mzstatic.com/image/thumb/AMCArtistImages221/v4/29/14/e7/2914e710-74c6-4060-cd32-2025bdafc682/ami-identity-04a903f68576367348771e6afe5a9f5d-2026-02-18T08-19-14.168Z_cropped.png/600x600cc.webp",
    "appleMusicUrl": "https://music.apple.com/us/artist/hearts2hearts/1793698498?uo=4",
    "fetchStatus": "success"
  },
  "kiiikiii": {
    "id": "kiiikiii",
    "sourceArtistName": "KiiiKiii",
    "sourceArtistImageUrl": "https://is1-ssl.mzstatic.com/image/thumb/AMCArtistImages221/v4/a6/68/cd/a668cd38-b40c-e870-21c2-888beaddbe07/ami-identity-f61c452aaedba0cc658b66685dbfca7c-2026-01-20T07-30-00.442Z_cropped.png/600x600cc.webp",
    "appleMusicUrl": "https://music.apple.com/us/artist/kiiikiii/1795471746?uo=4",
    "fetchStatus": "success"
  },
  "kpop-demon-hunters": {
    "id": "kpop-demon-hunters",
    "sourceArtistName": "KPop Demon Hunters Cast",
    "sourceArtistImageUrl": "https://is1-ssl.mzstatic.com/image/thumb/Music211/v4/e1/15/42/e1154273-8ecd-5702-e6e6-597f28001681/25UMGIM82363.rgb.jpg/600x600cc.webp",
    "appleMusicUrl": "https://music.apple.com/us/artist/kpop-demon-hunters-cast/1820264140?uo=4",
    "fetchStatus": "success"
  },
  "huntr-x": {
    "id": "huntr-x",
    "sourceArtistName": "HUNTR/X",
    "sourceArtistImageUrl": "https://is1-ssl.mzstatic.com/image/thumb/Features211/v4/ac/3c/e6/ac3ce606-56c5-6888-3a78-a4dd06d7f64b/mzl.iqphppow.jpg/600x600cc.webp",
    "appleMusicUrl": "https://music.apple.com/us/artist/huntr-x/1478164763?uo=4",
    "fetchStatus": "success"
  },
  "saja-boys": {
    "id": "saja-boys",
    "sourceArtistName": "Saja Boys",
    "sourceArtistImageUrl": "https://is1-ssl.mzstatic.com/image/thumb/Features221/v4/99/2e/aa/992eaa8b-bf30-b9ad-f165-7fba31f7cadb/mzl.jlqrjuyf.jpg/600x600cc.webp",
    "appleMusicUrl": "https://music.apple.com/us/artist/saja-boys/1820264141?uo=4",
    "fetchStatus": "success"
  },
  "love-and-deepspace": {
    "id": "love-and-deepspace",
    "sourceArtistName": "Love and Deepspace",
    "sourceArtistImageUrl": "https://is1-ssl.mzstatic.com/image/thumb/Music211/v4/bb/51/45/bb514590-d78f-0d2c-f5c4-3948249148fd/cover.jpg/600x600cc.webp",
    "appleMusicUrl": "https://music.apple.com/us/artist/love-and-deepspace/1724734035?uo=4",
    "fetchStatus": "success"
  },
  "radwimps": {
    "id": "radwimps",
    "sourceArtistName": "RADWIMPS",
    "sourceArtistImageUrl": "https://is1-ssl.mzstatic.com/image/thumb/AMCArtistImages211/v4/4a/75/bc/4a75bc16-6bda-e8aa-966a-03782b12f595/ami-identity-60e298455bd895221b74629334666db7-2025-09-16T10-33-42.930Z_cropped.png/600x600cc.webp",
    "appleMusicUrl": "https://music.apple.com/us/artist/radwimps/91160335?uo=4",
    "fetchStatus": "success"
  },
  "kenshi-yonezu": {
    "id": "kenshi-yonezu",
    "sourceArtistName": "Kenshi Yonezu",
    "sourceArtistImageUrl": "https://is1-ssl.mzstatic.com/image/thumb/Features211/v4/fd/e5/52/fde552df-0d89-ed0a-26b2-ab329e7bf771/mzl.jvktgnqe.jpg/600x600cc.webp",
    "appleMusicUrl": "https://music.apple.com/us/artist/kenshi-yonezu/530814268?uo=4",
    "fetchStatus": "success"
  },
  "mika-nakashima": {
    "id": "mika-nakashima",
    "sourceArtistName": "Mika Nakashima",
    "sourceArtistImageUrl": "https://is1-ssl.mzstatic.com/image/thumb/Features221/v4/b2/ec/f5/b2ecf5fb-0aa4-cfa8-9cd1-f44593415366/mzl.gmbxwzne.jpg/600x600cc.webp",
    "appleMusicUrl": "https://music.apple.com/us/artist/mika-nakashima/292677928?uo=4",
    "fetchStatus": "success"
  },
  "penny": {
    "id": "penny",
    "sourceArtistName": "戴佩妮",
    "sourceArtistImageUrl": "https://i.scdn.co/image/ab6761610000e5eb4f44c4e976662704e6c86a3d",
    "fetchStatus": "success"
  },
  "billie-eilish": {
    "id": "billie-eilish",
    "sourceArtistName": "Billie Eilish",
    "sourceArtistImageUrl": "https://is1-ssl.mzstatic.com/image/thumb/AMCArtistImages211/v4/e1/f3/6a/e1f36a60-9897-162d-3697-7501eeafbc3b/a1d41336-49bd-4212-8787-57547ca3f87e_ami-identity-ef10a72d4764d04743b17fa13520b756-2024-04-08T15-24-54.609Z_cropped.png/600x600cc.webp",
    "appleMusicUrl": "https://music.apple.com/us/artist/billie-eilish/1065981054?uo=4",
    "fetchStatus": "success"
  },
  "shakira": {
    "id": "shakira",
    "sourceArtistName": "Shakira",
    "sourceArtistImageUrl": "https://is1-ssl.mzstatic.com/image/thumb/AMCArtistImages211/v4/36/01/99/360199a8-ace1-44d8-485c-9bac313243bf/17fec21b-d273-4b10-83bf-918a22f14b85_file_cropped.png/600x600cc.webp",
    "appleMusicUrl": "https://music.apple.com/us/artist/shakira/889327?uo=4",
    "fetchStatus": "success"
  },
  "jennie": {
    "id": "jennie",
    "sourceArtistName": "JENNIE",
    "sourceArtistImageUrl": "https://i.scdn.co/image/ab6761670000ecd49c9554701f4364b48e3922b9",
    "fetchStatus": "success"
  },
  "itzy": {
    "id": "itzy",
    "sourceArtistName": "ITZY",
    "sourceArtistImageUrl": "https://i.scdn.co/image/ab6761610000e5eb81c00b4e062603d8159b1ad8",
    "fetchStatus": "success"
  },
  "newjeans": {
    "id": "newjeans",
    "sourceArtistName": "NewJeans",
    "sourceArtistImageUrl": "https://i.scdn.co/image/ab6761610000e5eb9d09a2503901f4364b48e392",
    "fetchStatus": "success"
  },
  "kep1er": {
    "id": "kep1er",
    "sourceArtistName": "Kep1er",
    "sourceArtistImageUrl": "https://i.scdn.co/image/ab6761610000e5eb0fb30f769312a6dfcad93802",
    "fetchStatus": "success"
  },
  "triples": {
    "id": "triples",
    "sourceArtistName": "tripleS",
    "sourceArtistImageUrl": "https://i.scdn.co/image/ab6761610000e5eb21b068e370397576f3f019a3",
    "fetchStatus": "success"
  },
  "babymonster": {
    "id": "babymonster",
    "sourceArtistName": "BABYMONSTER",
    "sourceArtistImageUrl": "https://i.scdn.co/image/ab6761610000e5eb98165c27632607f28de314f3",
    "fetchStatus": "success"
  },
  "g-dragon": {
    "id": "g-dragon",
    "sourceArtistName": "权志龙",
    "sourceArtistImageUrl": "https://i.scdn.co/image/ab6761610000e5ebe814c26d8f9ce7211f3d74e0",
    "fetchStatus": "success"
  },
  "mao-buyi": {
    "id": "mao-buyi",
    "sourceArtistName": "毛不易",
    "sourceArtistImageUrl": "https://i.scdn.co/image/ab6761610000e5eb0a850966dd447da548c67c66",
    "fetchStatus": "success"
  },
  "wang-yi-bo": {
    "id": "wang-yi-bo",
    "sourceArtistName": "王一博",
    "sourceArtistImageUrl": "https://i.scdn.co/image/ab6761610000e5eb730c4e10b147326e0dd96277",
    "fetchStatus": "success"
  },
  "wang-lee-hom": {
    "id": "wang-lee-hom",
    "sourceArtistName": "王力宏",
    "sourceArtistImageUrl": "https://i.scdn.co/image/ab6761610000e5eb66e39bed3767e6c721cf0cff5",
    "fetchStatus": "success"
  },
  "karen-mok": {
    "id": "karen-mok",
    "sourceArtistName": "莫文蔚",
    "sourceArtistImageUrl": "https://i.scdn.co/image/ab6761610000e5eb7c0678c170a417c80529d77c",
    "fetchStatus": "success"
  },
  "khalil-fong": {
    "id": "khalil-fong",
    "sourceArtistName": "方大同",
    "sourceArtistImageUrl": "https://i.scdn.co/image/ab6761610000e5eba0df2d59f0ae9426cba3eb36",
    "fetchStatus": "success"
  },
  "patrick-brasca": {
    "id": "patrick-brasca",
    "sourceArtistName": "派伟俊",
    "sourceArtistImageUrl": "https://i.scdn.co/image/ab6761670000ecd4ded8159b1ad8a0df2d59f0ae",
    "fetchStatus": "success"
  },
  "sean-tang": {
    "id": "sean-tang",
    "sourceArtistName": "唐汉霄",
    "sourceArtistImageUrl": "https://i.scdn.co/image/ab6761610000e5ebcbd1cc12df2edce693006a8e",
    "fetchStatus": "success"
  },
  "ding-yu-xi": {
    "id": "ding-yu-xi",
    "sourceArtistName": "丁禹兮",
    "sourceArtistImageUrl": "https://i.scdn.co/image/ab6761610000e5eb1d1c8f1e92e0e231b0689618",
    "fetchStatus": "success"
  },
  "qiao-jun-cheng": {
    "id": "qiao-jun-cheng",
    "sourceArtistName": "乔浚丞",
    "sourceArtistImageUrl": "https://i.scdn.co/image/ab6761610000e5eb9807cc90c379899f8d5f3d74",
    "fetchStatus": "success"
  },
  "zhang-bi-chen": {
    "id": "zhang-bi-chen",
    "sourceArtistName": "张碧晨",
    "sourceArtistImageUrl": "https://i.scdn.co/image/ab6761610000e5eba0287210634cf47b7211f3d7",
    "fetchStatus": "success"
  },
  "angela-szu-han-chang": {
    "id": "angela-szu-han-chang",
    "sourceArtistName": "张韶涵",
    "sourceArtistImageUrl": "https://i.scdn.co/image/ab6761610000e5ebba996c4b26d8f9ce7211f3d7",
    "fetchStatus": "success"
  },
  "ryuichi-sakamoto": {
    "id": "ryuichi-sakamoto",
    "sourceArtistName": "坂本龙一",
    "sourceArtistImageUrl": "https://i.scdn.co/image/ab6761670000ecd416be70258162208a0d014f3b",
    "fetchStatus": "success"
  },
  "mai-kuraki": {
    "id": "mai-kuraki",
    "sourceArtistName": "仓木麻衣",
    "sourceArtistImageUrl": "https://i.scdn.co/image/ab6761610000e5eb38ee899de61f8563676c721c",
    "fetchStatus": "success"
  },
  "black-myth-wukong": {
    "id": "black-myth-wukong",
    "sourceArtistName": "黑神话：悟空",
    "sourceArtistImageUrl": "https://image.api.playstation.com/vulcan/ap/rnd/202406/0403/dd924f331f41748383c27e390c54150101.png",
    "fetchStatus": "success"
  },
  "deadpool": {
    "id": "deadpool",
    "sourceArtistName": "Deadpool",
    "sourceArtistImageUrl": "https://pbs.twimg.com/media/GOfUo3_WAAA6p3k.jpg",
    "fetchStatus": "success"
  },
  "wolverine": {
    "id": "wolverine",
    "sourceArtistName": "Wolverine",
    "sourceArtistImageUrl": "https://pbs.twimg.com/media/GOfUo4AWYAAwXo_.jpg",
    "fetchStatus": "success"
  }
};
